version: '1.0'
#ronnya by Orb-H, omija_tea
#TODO: router healthcheck 이후 client,worker시작
#      올바른 종료 후 restart
#      환경변수 injection으로 국가/uid/token 변경

services:
  client:
    container_name: client
    image: playjnj/ronnya_client:1.0
    ports:
      - "5000:5000"
    env_file:
      - ./config/.env.client.container
    depends_on:
      router:
        condition: service_started #router가 복잡해지면 healthcheck 추가해야함
  router:
    container_name: router
    image: playjnj/ronnya_router:1.0.2
    env_file:
      - ./config/.env.router.container
  worker:
    container_name: worker
    image: playjnj/ronnya_worker:1.0
    env_file:
      - ./config/.env.worker.container
    depends_on:
      router:
        condition: service_started #router가 복잡해지면 healthcheck 추가해야함