version: '1.1'
services:
  nginx:
    container_name: nginx
    image: ronnya/nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./front:/usr/src/front
      - ./log:/var/log/nginx

  front:
    container_name: front
    image: ronnya/front
    build:
      context: ./front
      dockerfile: Dockerfile
    restart: always
    command: uwsgi --ini uwsgi.ini
    volumes:
      - ./front:/usr/src/front
      - ./log:/var/log/uwsgi/front
    environment:
    - SECRET_KEY=$(FRONT_SECRET_KEY)